"""
Prompts module for ZipAct.
Provides environment-specific prompts for different datasets.
"""

from .prompt_manager import (
    PromptManager,
    get_zipact_prompts,
    get_react_prompts,
)

# ALFWorld prompts (default)
from .zipact_prompts import (
    ZIPACT_UPDATER_SYSTEM_PROMPT,
    ZIPACT_ACTOR_SYSTEM_PROMPT,
    ZIPACT_INIT_STATE_PROMPT,
    ALFWORLD_ZIPACT_UPDATER_SYSTEM_PROMPT,
    ALFWORLD_ZIPACT_ACTOR_SYSTEM_PROMPT,
    ALFWORLD_ZIPACT_INIT_STATE_PROMPT,
)

from .react_prompts import (
    REACT_SYSTEM_PROMPT,
    REACT_INSTRUCTION_TEMPLATE,
    ALFWORLD_REACT_SYSTEM_PROMPT,
    ALFWORLD_REACT_INSTRUCTION_TEMPLATE,
)

# SciWorld prompts
from .sciworld_prompts import (
    SCIWORLD_ZIPACT_UPDATER_SYSTEM_PROMPT,
    SCIWORLD_ZIPACT_ACTOR_SYSTEM_PROMPT,
    SCIWORLD_ZIPACT_INIT_STATE_PROMPT,
    SCIWORLD_REACT_SYSTEM_PROMPT,
    SCIWORLD_REACT_INSTRUCTION_TEMPLATE,
)

# WebShop prompts
from .webshop_prompts import (
    WEBSHOP_ZIPACT_UPDATER_SYSTEM_PROMPT,
    WEBSHOP_ZIPACT_ACTOR_SYSTEM_PROMPT,
    WEBSHOP_ZIPACT_INIT_STATE_PROMPT,
    WEBSHOP_REACT_SYSTEM_PROMPT,
    WEBSHOP_REACT_INSTRUCTION_TEMPLATE,
)

__all__ = [
    # Manager
    "PromptManager",
    "get_zipact_prompts",
    "get_react_prompts",
    # ALFWorld (default)
    "ZIPACT_UPDATER_SYSTEM_PROMPT",
    "ZIPACT_ACTOR_SYSTEM_PROMPT",
    "ZIPACT_INIT_STATE_PROMPT",
    "REACT_SYSTEM_PROMPT",
    "REACT_INSTRUCTION_TEMPLATE",
    # ALFWorld explicit
    "ALFWORLD_ZIPACT_UPDATER_SYSTEM_PROMPT",
    "ALFWORLD_ZIPACT_ACTOR_SYSTEM_PROMPT",
    "ALFWORLD_ZIPACT_INIT_STATE_PROMPT",
    "ALFWORLD_REACT_SYSTEM_PROMPT",
    "ALFWORLD_REACT_INSTRUCTION_TEMPLATE",
    # SciWorld
    "SCIWORLD_ZIPACT_UPDATER_SYSTEM_PROMPT",
    "SCIWORLD_ZIPACT_ACTOR_SYSTEM_PROMPT",
    "SCIWORLD_ZIPACT_INIT_STATE_PROMPT",
    "SCIWORLD_REACT_SYSTEM_PROMPT",
    "SCIWORLD_REACT_INSTRUCTION_TEMPLATE",
    # WebShop
    "WEBSHOP_ZIPACT_UPDATER_SYSTEM_PROMPT",
    "WEBSHOP_ZIPACT_ACTOR_SYSTEM_PROMPT",
    "WEBSHOP_ZIPACT_INIT_STATE_PROMPT",
    "WEBSHOP_REACT_SYSTEM_PROMPT",
    "WEBSHOP_REACT_INSTRUCTION_TEMPLATE",
]
